spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://2c4g6m.test.ev:13306/watermark_remove?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: username
    #如果你的密码是纯数字，需要用字符串包起来，只有纯数字需要这样
    password: 'password'

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  port: 10521
wx:
  appId: appId
  secret: secrety

logging:
  file:
    name: ./logs/watermark.log
  level:
    root: ERROR
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
