

server:
  port: 10521


spring:
  profiles:
    active: dev


  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false



logging:
  file:
    name: ./logs/watermark.log
  level:
    root: ERROR
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
